select * from customer limit 10
--1. Revenue by Gender – Compared total revenue generated by male vs. female customers. 
select gender ,sum(purchase_amount) as revenue from customer
group by gender;

/*2. High-Spending Discount Users – Identified customers who used discounts but still 
spent above the average purchase amount. */
select customer_id , purchase_amount from customer 
where (discount_applied = 'Yes') and (purchase_amount>= (select AVG(purchase_amount) from customer));

--Top 5 Products by Rating – Found products with the highest average review ratings.
select item_purchased , round(AVG(review_rating::numeric),2) AS average_product_rating 
from customer
group by  item_purchased 
order by AVG(review_rating) 
desc limit 5;

/* 4. Shipping Type Comparison – Compared average purchase amounts between 
Standard and Express shipping. */
select shipping_type , round(avg(purchase_amount),2) as average_purchase_amount from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

/* 5. Subscribers vs. Non-Subscribers – Compared average spend and 
total revenue across subscription status.*/
select subscription_status ,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as aveage_purchase_amount ,
sum(purchase_amount) as total_revenue
from customer 
group by subscription_status 
order by total_revenue desc;

/*6. Discount-Dependent Products – Identified 5 products with the highest percentage of 
discounted purchases.*/
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0  end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc 
limit 5;


/* 7 Customer Segmentation – Classified customers into New, Returning, and Loyal 
segments based on purchase history. */

with customer_type as (
select customer_id,previous_purchases,
case
    when previous_purchases=1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
from customer)

select customer_segment ,count(*) as "number of customers"
from customer_type
group by customer_segment 
order by "number of customers" desc;

/* 8. Top 3 Products per Category – Listed the most purchased products within each 
category.*/


